title = "One Revolution Website Netlify Configuration File"

[build]
    publish = "dist"
    command = "pnpm run build"

[dev]
    framework = "nuxt"
    command = "pnpm run dev" # Command to start your dev server
    port = 8000
    publish = "dist" # The path to your static content folder
    autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser


[build.environment]
    NODE_VERSION = "22.16.0"
    NODE_OPTIONS = "--max-old-space-size=4096"



[[headers]]
    for = "/manifest.webmanifest"
[headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
    for = "/assets/*"
[headers.values]
    cache-control = '''
            max-age=31536000,
            immutable
            '''
[context.branch-deploy]
    command = "NODE_OPTIONS=\"--max-old-space-size=4096\" pnpm run build"
